name: "Run linter"

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download golangci-lint config
        run: curl -sS https://raw.githubusercontent.com/adlandh/golangci-lint-config/refs/heads/main/.golangci.yml -o .golangci.yml

      - name: Lint Code Base
        uses: golangci/golangci-lint-action@v6

      - name: Lint Code Base (sentry-extractor)
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./sentry-extractor

      - name: Lint Code Base (otel-extractor)
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: ./otel-extractor
