name: "Run linter"

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Lint Code Base
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          install-mode: goinstall

      - name: Lint Code Base (sentry-extractor)
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          install-mode: goinstall
          workdir: sentry-extractor

      - name: Lint Code Base (otel-extractor)
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          install-mode: goinstall
          workdir: otel-extractor
